os: windows
language: bash
services: docker
script: 
- docker version
- docker images
- winpty docker run -it mcr.microsoft.com/windows/nanoserver env
- winpty docker pull ruby:3.0.0
- winpty docker run -it ruby:3.0.0 env
